spring.datasource.url=jdbc:postgresql://localhost:5432/Payments
spring.datasource.username=postgres
spring.datasource.password=1111
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always
spring.main.allow-bean-definition-overriding=true

spring.security.oauth2.client.registration.auth0.client-id=zTmBgBIVupr7hXAJMuGOPzRlIq3KEVyc
spring.security.oauth2.client.registration.auth0.client-secret=0h1bpV_lWeyV45lsAbFEJywzz5sN6iPTl-27cn6gmXMXbHoljf6dbywTijmlGUKF
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email
spring.security.oauth2.client.registration.auth0.redirect-uri=http://localhost:3000/login/oauth2/code/auth0

spring.security.oauth2.client.provider.auth0.issuer-uri=https://dev-e3n1otn0qq2n0tiy.us.auth0.com/

# Auth0 (Okta) OAuth2 configuration

spring.security.oauth2.client.provider.auth0.authorization-uri=https://dev-e3n1otn0qq2n0tiy.us.auth0.com/authorize
spring.security.oauth2.client.provider.auth0.token-uri=https://dev-e3n1otn0qq2n0tiy.us.auth0.com/oauth/token
spring.security.oauth2.client.provider.auth0.user-info-uri=https://dev-e3n1otn0qq2n0tiy.us.auth0.com/userinfo
spring.security.oauth2.client.provider.auth0.jwk-set-uri=https://dev-e3n1otn0qq2n0tiy.us.auth0.com/.well-known/jwks.json

spring.security.oauth2.client.provider.auth0.user-name-attribute=sub
